services :
  app:
    build: .
    volumes :
      - .:/mental_ai
    ports:
      [8000:8000]
    env_file:
      - .env
    image: app:mental_ai
    container_name: mental_ai
    environment:
      - DEBUG = True
      - DJANGO_ENV=local
      - CHROMA_DB_HOST=http://chromadb:8000
    command: [./entrypoint.sh]
    depends_on:
      - chromadb


  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    restart: always
    ports:
      - "8000:8000"