# Generated by Django 5.1.6 on 2025-04-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_videomeditaion_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomeditaion',
            old_name='video',
            new_name='video_partial_id',
        ),
    ]
